### ISSUE TITLE
为什么一直显示加载中

### ISSUE THREAD

**Issue by Sure-Plus** [jiajiayao/ZhiHuiShu_Get_Answer_chrome_plugins#7]

**Comment by jiajiayao** [comment]
好了

**Comment by jiajiayao** [comment]
我好像被别人攻击了/xk

**Comment by jiajiayao** [comment]
![image](https://user-images.githubusercontent.com/48589551/83322981-2ea76700-a28e-11ea-9af6-7f8ff5b9080b.png)
重启中

**Comment by Sure-Plus** [comment]
好哒，谢谢作者

**Comment by jiajiayao** [comment]
记得点个star，follow




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sure-Plus"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月30日(星期六) 下午3:59
收件人:&nbsp;"jiajiayao/ZhiHuiShu_Get_Answer_chrome_plugins"<ZhiHuiShu_Get_Answer_chrome_plugins@noreply.github.com&gt;;
抄送:&nbsp;"风凡"<jiajiayaoabc@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jiajiayao/ZhiHuiShu_Get_Answer_chrome_plugins] 为什么一直显示加载中 (#7)





 
好哒，谢谢作者

**Comment by jiajiayao** [comment]
好了
